let college = [
    {
        name: 'COEP = College Of Engineering Pune',
        location: 'pune',
        fee: 65000,
        intake: 12,
        cutoff_lastYear: "SC:95.09 | OBC:97.03",
        placement: 79.53,
        average: 6.5,
        highest: 39,
        top15: true,
        priority: 3,
        government: true,
    },
    {
        name: 'Government College of Engineering',
        location: 'karad',
        fee: 65000,
        intake: 6,
        alert: "<i>Only IT department is available</i>",
        cutoff_lastYear: "SC:93.43 | OBC:93.03",
        placement: 85,
        average: 4.5,
        highest: 12,
        top15: true,
        government: true,
    },
    {
        name: 'Government College of Engineering',
        location: 'jalgaon',
        fee: 82956,
        intake: -1,
        placement: -1,
        average: 3.5,
        highest: 7.5,
        government: true,
    },
    {
        name: 'Government College of Engineering',
        location: 'chandrapur',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1,
        government: true,
    },
    {
        name: 'Government College of Engineering',
        location: 'nagpur',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1,
        government: true,
    },
    {
        name: 'Government College of Engineering and Research Avsari',
        location: 'pune',
        fee: 28000,
        intake: 11,
        cutoff_lastYear: "SC: 90.17 | OBC: 92.63",
        placement: 60,
        average: 3.5,
        highest: 9,
        top15: true,
        government: true,
        priority: 10,
    },
    {
        name: 'Government College of Engineering',
        location: 'amravati',
        fee: -1,
        intake: 10,
        cutoff_lastYear: "SC: 90.13 | OBC: 92.86",
        placement: -1,
        average: 4.3,
        highest: 17,
        government: true,
        priority: 15,
    },
    {
        name: 'Government College of Engineering',
        location: 'yavatmal',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1,
        government: true,
    },
    {
        name: 'Government College of Engineering',
        location: 'aurangabad',
        fee: 25000,
        intake: 9,
        cutoff_lastYear: "SC:91 | OBC: 93.20",
        placement: 60,
        average: 3.6,
        highest: 8,
        top15: true,
        government: true,
        priority: 11,
    },
    {
        name: 'Jawaharlal Nehru Engineering College (MGM University)',
        location: 'aurangabad',
        fee: 155000,
        intake: 12,
        placement: -1,
        average: -1,
        highest: 22,
    },
    {
        name: 'VJTI = Veermata Jijabai Technological Institute',
        location: 'mumbai',
        aided: "YES",
        fee: 82000,
        intake: 8,
        cutoff_lastYear: "SC:95.33 | OBC:97.31",
        placement: 74.04,
        average: 7.65,
        highest: 36,
        top15: true,
        priority: 1,
        government: true,
    },
    {
        name: 'VIT = Vishvakarma Institute of Technology',
        location: 'pune',
        fee: 170000,
        intake: 31,
        cutoff_lastYear: "SC:92.97 | OBC:94.91",
        placement: 72,
        average: 5.5,
        highest: 28,
        top15: true,
        priority: 6,
    },
    {
        name: 'VNIT = Vishvesvarya National Institute of Technology',
        location: 'nagpur',
        fee: 100000,
        intake: -1,
        placement: 70,
        average: 6.5,
        highest: 22,
        top15: true,
    },
    {
        name: 'Shree Guru Gobind Singhji Institute of Engineering and Technology',
        location: 'nanded',
        aided: "YES",
        fee: 60000,
        intake: 15,
        cutoff_lastYear: "SC: 90.97 | OBC: 93.20",
        placement: 55,
        average: 5,
        highest: 12,
        top15: true,
        government: true,
    },
    {
        name: 'Yashwantrao Chavhan College of Engineering',
        location: 'nagpur',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1
    }, {
        name: 'WCE = Walchand College Of Engineering',
        location: 'sangli',
        aided: "YES",
        fee: 85000,
        intake: 12,
        cutoff_lastYear: "SC: 92.75 | OBC: 95.19",
        placement: 70,
        average: 5,
        highest: 21,
        top15: true,
        government: true,
        priority: 7,
    },
    {
        name: 'Shree Ramdevbaba College of Engineering',
        location: 'nagpur',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1,
    },
    {
        name: 'PICT = Pune Institute Of Computer Technology',
        location: 'pune',
        fee: 95000,
        intake: 27,
        cutoff_lastYear: "SC:93.83 | OBC:96.00",
        placement: 85,
        average: 5,
        highest: 16.5,
        priority: 4,
        top15: true,
    },
    {
        name: 'PCCOE = Pimpri Chinchwad College of Engineering',
        location: 'pune',
        fee: 140000,
        intake: 26,
        cutoff_lastYear: "SC: 91.69 | OBC: 93.94",
        placement: 55,
        average: 6.5,
        highest: 11,
        top15: true,
        priority: 8,
    },
    {
        name: 'MIT-WPU = MIT World Peace University',
        location: 'pune',
        fee: 310000,
        intake: -1,
        placement: 80,
        average: 3,
        highest: 37,
        top15: true,
    },
    {
        name: 'VIIT = Vishvakarma Institute of Information Technology',
        location: 'pune',
        fee: -1,
        intake: -1,
        placement: 55,
        average: -1,
        highest: -1,
        priority: 9,
    },
    {
        name: 'Sinhagad College of Pune',
        location: 'pune',
        fee: -1,
        intake: 24,
        cutoff_lastYear: "SC: 88 | OBC: 91.42",
        placement: -1,
        average: -1,
        highest: -1,
        priority: 14,
    },
    {
        name: 'Modern College of Engineering Pune',
        location: 'pune',
        fee: 5739,
        'fee for OBC': 60543,
        intake: 12,
        cutoff_lastYear: "SC: 88.92 |OBC: 90.63",
        placement: -1,
        average: 4,
        highest: -1
    },
    {
        name: 'Dr. D.Y.Patil Institute of Technology',
        location: 'pune',
        fee: 130000,
        intake: 17,
        cutoff_lastYear: "SC:88.97 | OBC:92.57",
        placement: 50,
        average: 4.5,
        highest: 30,
        top15: true,
        priority: 12,
    },
    {
        name: 'All India Shri Shivaji Memorial Society College of Engineering',
        location: 'pune',
        fee: 140000,
        intake: 9,
        cutoff_lastYear: "SC: 88.40 | OBC: 91.77",
        placement: 50,
        average: 4,
        highest: 12,
        top15: true,
        priority: 13,
    },
    {
        name: 'Sardar Patel Institute of Technology',
        location: 'mumbai',
        aided: "YES",
        fee: 11550,
        intake: 7,
        cutoff_lastYear: "SC:96.69 | OBC:95.03",
        placement: 100,
        average: 11,
        highest: 42,
        top15: true,
        priority: 2,
        government: true,
    },
    {
        name: 'DJ Sanghli = Dwarkadas Jeevandas Sanghli',
        location: 'mumbai',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1
    },
    {
        name: 'Somya college',
        location: 'mumbai',
        fee: -1,
        intake: 6,
        placement: -1,
        average: -1,
        highest: -1
    },
    {
        name: 'VESIT = Vivekanand Education Society Institute of Technology',
        location: 'mumbai',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1
    },
    {
        name: 'TSEC = Thadomal Shahani Engineering College',
        location: 'mumbai',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1,
    },
    {
        name: 'RAIT = Ramrao Adik Institute of Technology',
        location: 'mumbai',
        fee: -1,
        intake: -1,
        placement: -1,
        average: -1,
        highest: -1,
    },
    {
        name: 'Bharti Vidyapeeth College of Engineering',
        location: 'pune',
        fee: 120000,
        intake: -1,
        placement: -1,
        average: 7,
        highest: 12,
        priority:5,
    },
    {
        name: 'DKTE Society\'s Textile and Engineering Institute, ichalkaranji',
        location: 'kolhapur',
        fee: 100000,
        intake: 12,
        placement: 90,
        average: 4,
        highest: -1,
    },

];